#!/usr/bin/env python3
"""Convert Familiar's tabby-cat pack into deterministic ESP8266 assets."""

from __future__ import annotations

import argparse
import hashlib
import io
from pathlib import Path
import sys

from PIL import Image

STATES = (
    "idle",
    "working",
    "thinking",
    "interacting",
    "happy",
    "celebrating",
    "alarmed",
    "sleeping",
    "watching",
)
LOGICAL_SIZE = 96
DISPLAY_SIZE = 192
ALPHA_THRESHOLD = 96
OPAQUE_COLORS = 31


def alpha_aware_resize(image: Image.Image) -> Image.Image:
    rgba = image.convert("RGBA")
    alpha = rgba.getchannel("A")
    premultiplied = []
    for channel in rgba.convert("RGB").split():
        premultiplied.append(
            Image.frombytes(
                "L",
                rgba.size,
                bytes((value * mask + 127) // 255 for value, mask in zip(channel.tobytes(), alpha.tobytes())),
            )
        )
    resized_alpha = alpha.resize((LOGICAL_SIZE, LOGICAL_SIZE), Image.Resampling.LANCZOS)
    resized_channels = [
        channel.resize((LOGICAL_SIZE, LOGICAL_SIZE), Image.Resampling.LANCZOS)
        for channel in premultiplied
    ]
    alpha_bytes = resized_alpha.tobytes()
    straight_channels = []
    for channel in resized_channels:
        straight_channels.append(
            Image.frombytes(
                "L",
                resized_alpha.size,
                bytes(
                    0 if mask < ALPHA_THRESHOLD else min(255, (value * 255 + mask // 2) // mask)
                    for value, mask in zip(channel.tobytes(), alpha_bytes)
                ),
            )
        )
    cleaned_alpha = resized_alpha.point(lambda value: 255 if value >= ALPHA_THRESHOLD else 0)
    return Image.merge("RGBA", (*straight_channels, cleaned_alpha))


def shared_palette(images: dict[str, Image.Image]) -> Image.Image:
    samples = []
    for state in STATES:
        image = images[state]
        samples.extend(pixel[:3] for pixel in image.getdata() if pixel[3])
    sample_image = Image.new("RGB", (len(samples), 1))
    sample_image.putdata(samples)
    return sample_image.quantize(
        colors=OPAQUE_COLORS,
        method=Image.Quantize.MEDIANCUT,
        dither=Image.Dither.NONE,
    )


def index_image(image: Image.Image, palette: Image.Image) -> tuple[Image.Image, list[int]]:
    rgb = image.convert("RGB").quantize(palette=palette, dither=Image.Dither.NONE)
    alpha = image.getchannel("A").tobytes()
    logical = [0 if mask == 0 else index + 1 for index, mask in zip(rgb.tobytes(), alpha)]
    display = []
    for y in range(LOGICAL_SIZE):
        row = logical[y * LOGICAL_SIZE : (y + 1) * LOGICAL_SIZE]
        doubled = [value for value in row for _ in range(2)]
        display.extend(doubled)
        display.extend(doubled)
    preview = Image.new("P", (DISPLAY_SIZE, DISPLAY_SIZE))
    source_palette = palette.getpalette()[: OPAQUE_COLORS * 3]
    preview.putpalette([0, 0, 0] + source_palette + [0] * (768 - 3 - len(source_palette)))
    preview.putdata(display)
    preview.info["transparency"] = 0
    return preview, display


def rle_encode(indexes: list[int]) -> bytes:
    encoded = bytearray()
    for y in range(DISPLAY_SIZE):
        row = indexes[y * DISPLAY_SIZE : (y + 1) * DISPLAY_SIZE]
        start = 0
        while start < DISPLAY_SIZE:
            value = row[start]
            length = 1
            while start + length < DISPLAY_SIZE and row[start + length] == value and length < 255:
                length += 1
            encoded.extend((length, value))
            start += length
    return bytes(encoded)


def rle_decode(encoded: bytes) -> list[int]:
    decoded = []
    if len(encoded) % 2:
        raise ValueError("RLE stream must contain length/index pairs")
    for offset in range(0, len(encoded), 2):
        length, index = encoded[offset : offset + 2]
        if length == 0 or index > OPAQUE_COLORS:
            raise ValueError("invalid RLE pair")
        decoded.extend([index] * length)
    return decoded


def rgb565(red: int, green: int, blue: int) -> int:
    return ((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3)


def render_header(palette: Image.Image, encoded: dict[str, bytes], source_hash: str) -> bytes:
    colors = [0]
    raw_palette = palette.getpalette()
    for index in range(OPAQUE_COLORS):
        offset = index * 3
        colors.append(rgb565(*raw_palette[offset : offset + 3]))
    lines = [
        "// Generated by tools/convert_tabby_assets.py; do not edit.",
        f"// Source SHA-256: {source_hash}",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        "namespace familiar::assets {",
        f"constexpr uint16_t kSpriteWidth = {DISPLAY_SIZE};",
        f"constexpr uint16_t kSpriteHeight = {DISPLAY_SIZE};",
        f"constexpr uint8_t kPaletteSize = {len(colors)};",
        "const uint16_t kPalette[kPaletteSize] PROGMEM = {",
        "    " + ", ".join(f"0x{color:04X}" for color in colors),
        "};",
        "",
        "struct SpriteAsset { const uint8_t* data; uint32_t length; };",
        "",
    ]
    for state in STATES:
        symbol = "k" + "".join(word.title() for word in state.split("_"))
        payload = encoded[state]
        lines.append(f"const uint8_t {symbol}[] PROGMEM = {{")
        for offset in range(0, len(payload), 24):
            lines.append("    " + ", ".join(str(value) for value in payload[offset : offset + 24]) + ",")
        lines.extend(("};", ""))
    lines.append("const SpriteAsset kSprites[] PROGMEM = {")
    for state in STATES:
        symbol = "k" + "".join(word.title() for word in state.split("_"))
        lines.append(f"    {{{symbol}, sizeof({symbol})}},")
    lines.extend(("};", "", "}  // namespace familiar::assets", ""))
    return "\n".join(lines).encode()


def png_bytes(image: Image.Image) -> bytes:
    output = io.BytesIO()
    image.save(output, format="PNG", optimize=False, compress_level=9)
    return output.getvalue()


def build(source_dir: Path) -> dict[Path, bytes]:
    source_hash = hashlib.sha256()
    resized = {}
    for state in STATES:
        source = source_dir / f"{state}.png"
        if not source.is_file():
            raise FileNotFoundError(f"missing source state: {source}")
        data = source.read_bytes()
        source_hash.update(state.encode())
        source_hash.update(data)
        with Image.open(io.BytesIO(data)) as image:
            if image.size != (1024, 1024):
                raise ValueError(f"{source} must use the shared 1024x1024 canvas")
            resized[state] = alpha_aware_resize(image)

    palette = shared_palette(resized)
    previews = {}
    encoded = {}
    indexed = {}
    for state in STATES:
        preview, indexes = index_image(resized[state], palette)
        previews[Path("preview") / f"{state}.png"] = png_bytes(preview)
        indexed[state] = preview
        encoded[state] = rle_encode(indexes)
        if rle_decode(encoded[state]) != indexes:
            raise AssertionError(f"RLE round trip failed for {state}")
        if preview.size != (DISPLAY_SIZE, DISPLAY_SIZE) or max(indexes) > OPAQUE_COLORS:
            raise AssertionError(f"invalid indexed preview for {state}")

    sheet = Image.new("RGBA", (DISPLAY_SIZE * 3, DISPLAY_SIZE * 3), (0, 0, 0, 0))
    for index, state in enumerate(STATES):
        sheet.alpha_composite(indexed[state].convert("RGBA"), ((index % 3) * DISPLAY_SIZE, (index // 3) * DISPLAY_SIZE))
    previews[Path("preview") / "contact-sheet.png"] = png_bytes(sheet)
    previews[Path("src") / "generated" / "tabby_assets.h"] = render_header(
        palette, encoded, source_hash.hexdigest()
    )
    return previews


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = build(args.source)
    stale = []
    for relative, content in outputs.items():
        destination = args.output / relative
        if args.check:
            if not destination.is_file() or destination.read_bytes() != content:
                stale.append(str(destination))
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        if not destination.is_file() or destination.read_bytes() != content:
            destination.write_bytes(content)
    if stale:
        print("generated assets are missing or stale:\n" + "\n".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
