[platformio]
default_envs = esp12f_st7735_128

[env:esp12f_st7735_128]
platform = espressif8266@4.2.1
board = d1_mini
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
extra_scripts = pre:scripts/generate_assets.py
build_src_filter = +<*> -<screen_diagnostic.cpp>
lib_deps =
    bodmer/TFT_eSPI@2.5.43
    links2004/WebSockets@2.6.1
    bblanchon/ArduinoJson@6.21.5
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -D USER_SETUP_LOADED=1
    -D ST7735_DRIVER=1
    -D ST7735_GREENTAB128=1
    -D TFT_HEIGHT=128
    -D TFT_WIDTH=128
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=0
    -D TFT_RST=2
    -D SPI_FREQUENCY=40000000
    -D LOAD_GLCD=1

[env:screen_diagnostic]
extends = env:esp12f_st7735_128
build_src_filter = +<screen_diagnostic.cpp>
extra_scripts =
